### ISSUE TITLE
Lazily evaluated caches

### ISSUE THREAD

**Issue by rofinn** [invenia/DataViews.jl#1]
Currently, the original DataView stores all values in a cache which is just an n-dimensional array of floats. Implementing other cache types for Variance (OnlineStats.jl) or Nullables won't be to hard, but we also need an abstraction for only storing part of a DataView in a smaller cache.

**Comment by Rory-Finnegan** [comment]
Bike Shedding:

Create a circular buffer array type which should probably be its own package. Then just use subarrays of the circular buffer as the cache for DataViews.

Circular Buffer:
* Store a 1-dimensional array, chunked by the size of the n-dimensional array used as the cache in the resulting DataViews.
* Maintain an array of current indices
